# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# If separate tagging of full version, major version, major-minor version, and latest version
# is needed, see the Tharsis API's .gitlab-ci.yml file for a pattern.
# However, the matrix strategy might be better.
#
# The build must be done here (duplicated from the build workflow) or the image is not available to tag and push.
#
############################################
#
# FIXME: Temporarily removed this:
#
#  name: publish
#   on:
#      push:
#      -    tags:
#      -      - 'v*'
#       permissions:
#
############################################
#
name: publish
on:
  push:
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        handler: [oidc, token]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
